"""Phase 9. The portable `.ctx` package.

The artifact the rest of the project exists to produce: what one agent knows,
written down so another can pick it up. Generated by ``build``, checked by
``validate``, read by ``render``.

    package, report = build(session_id=..., state=items, provenance=...)
    path.write_text(package.to_json())

    package = CtxPackage.from_json(path.read_text())
    print(validate(package))
    print(render(package))

See ``docs/ctx-format.md`` for what is in the format and why.
"""

from open_context.package.builder import EXCERPT_LIMIT, PackageBuildReport, build
from open_context.package.format import (
    FORMAT,
    FORMAT_VERSION,
    ArchiveReference,
    CtxPackage,
    EvidenceReference,
    Manifest,
    RecentContext,
)
from open_context.package.inspect import render, summarize
from open_context.package.security import Hazard, SecurityReport, review
from open_context.package.validation import (
    Depth,
    Finding,
    Severity,
    ValidationReport,
    format_report,
    validate,
)

__all__ = [
    "EXCERPT_LIMIT",
    "FORMAT",
    "FORMAT_VERSION",
    "ArchiveReference",
    "CtxPackage",
    "Depth",
    "EvidenceReference",
    "Finding",
    "Hazard",
    "Manifest",
    "PackageBuildReport",
    "RecentContext",
    "SecurityReport",
    "Severity",
    "ValidationReport",
    "build",
    "format_report",
    "render",
    "review",
    "summarize",
    "validate",
]
